### ISSUE TITLE
Error during message sending - no own devicelist

### ISSUE THREAD

**Issue by kurnevsky** [gkdr/lurch#29] opened 2017-02-27 12:06 UTC
When I try to send message with omemo pidgin writes:
```
(02:36:59 PM) There was an error encrypting the message and it was not sent. You can try again, or try to find the problem by looking at the debug log.
```
Error from debug window:
```
(14:36:59) lurch: lurch_message_encrypt_im: no own devicelist (0)
(14:36:59) g_log: xmlnode_to_str_helper: assertion 'node != NULL' failed
(14:36:59) g_log: jabber_send_raw: assertion 'data != NULL' failed
```

**Comment by gkdr** [comment] 2017-02-27 20:45
That's very weird. Maybe something went wrong during initialization? Does this error persist after a restart?

**Comment by vn971** [comment] 2017-02-27 20:57
@gkdr if anything, this happens on my system, too. Pidgin communicating with F-Droid version of Conversations. Though pidgin is communicating through jabber.ru server, which only supports parts of the necessary XEPs.

**Comment by gkdr** [comment] 2017-02-27 21:14
I queried jabber.ru and it does seem to support PEP, which is the one XEP that is needed. But it has a lot of weird pubsub stuff going on, maybe the configuration does not work well with it.
I am working with the F-Droid version of Conversations too and it doesn't happen, but it should not be related to it anyway. The devicelist should always be there, as a client should publish it if it's not.

If you can give me some more debug output from the very start of the program I can maybe try to find out the error.

**Comment by kurnevsky** [comment] 2017-02-28 09:18
@gkdr here you are:
```
(10:23:29) prefs: /pidgin/blist/x changed, scheduling save.
(10:23:29) prefs: /pidgin/conversations/im/y changed, scheduling save.
(10:23:29) prefs: /pidgin/debug/width changed, scheduling save.
(10:23:29) prefs: /pidgin/debug/height changed, scheduling save.
(10:23:29) prefs: /pidgin/blist/height changed, scheduling save.
(10:23:29) prefs: /pidgin/conversations/im/height changed, scheduling save.
(10:23:34) util: Writing file prefs.xml to directory /home/kurnevsky/.purple
(10:23:34) util: Writing file /home/kurnevsky/.purple/prefs.xml
(10:23:39) GLib: Source ID 34156 was not found when attempting to remove it
(10:23:41) GLib: Source ID 34161 was not found when attempting to remove it
(10:23:45) GLib: Source ID 34166 was not found when attempting to remove it
(10:23:45) GLib: Source ID 34171 was not found when attempting to remove it
(10:23:53) GLib: Source ID 34176 was not found when attempting to remove it
(10:23:54) GLib: Source ID 34181 was not found when attempting to remove it
(10:23:57) GLib: Source ID 34189 was not found when attempting to remove it
(10:24:00) GLib: Source ID 34194 was not found when attempting to remove it
(10:24:03) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(10:24:03) GdkPixbuf: 	Encoding raw
(10:24:03) GdkPixbuf: 	Dimensions: 16 x 16
(10:24:03) GdkPixbuf: 	Rowstride: 64, Length: 1048
(10:24:03) GdkPixbuf: 	Copy pixels == false
(10:24:03) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(10:24:03) GdkPixbuf: 	Encoding raw
(10:24:03) GdkPixbuf: 	Dimensions: 16 x 16
(10:24:03) GdkPixbuf: 	Rowstride: 64, Length: 1048
(10:24:03) GdkPixbuf: 	Copy pixels == false
(10:24:03) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(10:24:03) GdkPixbuf: 	Encoding raw
(10:24:03) GdkPixbuf: 	Dimensions: 16 x 16
(10:24:03) GdkPixbuf: 	Rowstride: 64, Length: 1048
(10:24:03) GdkPixbuf: 	Copy pixels == false
(10:24:03) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(10:24:03) GdkPixbuf: 	Encoding raw
(10:24:03) GdkPixbuf: 	Dimensions: 16 x 16
(10:24:03) GdkPixbuf: 	Rowstride: 64, Length: 1048
(10:24:03) GdkPixbuf: 	Copy pixels == false
(10:24:03) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(10:24:03) GdkPixbuf: 	Encoding raw
(10:24:03) GdkPixbuf: 	Dimensions: 16 x 16
(10:24:03) GdkPixbuf: 	Rowstride: 64, Length: 1048
(10:24:03) GdkPixbuf: 	Copy pixels == false
(10:24:03) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(10:24:03) GdkPixbuf: 	Encoding raw
(10:24:03) GdkPixbuf: 	Dimensions: 16 x 16
(10:24:03) GdkPixbuf: 	Rowstride: 64, Length: 1048
(10:24:03) GdkPixbuf: 	Copy pixels == false
(10:24:03) log: Failed to open log file "/home/kurnevsky/.purple/logs/<...>.log" for reading: No such file or directory
(10:24:03) gtkconv: setting active conversation on toolbar 0xa90d50
(10:24:03) prefs: /pidgin/conversations/toolbar/wide changed, scheduling save.
(10:24:03) gtkconv: setting active conversation on toolbar 0xa90d50
(10:24:03) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(10:24:03) GdkPixbuf: 	Encoding raw
(10:24:03) GdkPixbuf: 	Dimensions: 16 x 16
(10:24:03) GdkPixbuf: 	Rowstride: 64, Length: 1048
(10:24:03) GdkPixbuf: 	Copy pixels == false
(10:24:03) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(10:24:03) GdkPixbuf: 	Encoding raw
(10:24:03) GdkPixbuf: 	Dimensions: 16 x 16
(10:24:03) GdkPixbuf: 	Rowstride: 64, Length: 1048
(10:24:03) GdkPixbuf: 	Copy pixels == false
(10:24:03) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(10:24:03) GdkPixbuf: 	Encoding raw
(10:24:03) GdkPixbuf: 	Dimensions: 16 x 16
(10:24:03) GdkPixbuf: 	Rowstride: 64, Length: 1048
(10:24:03) GdkPixbuf: 	Copy pixels == false
(10:24:03) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(10:24:03) GdkPixbuf: 	Encoding raw
(10:24:03) GdkPixbuf: 	Dimensions: 16 x 16
(10:24:03) GdkPixbuf: 	Rowstride: 64, Length: 1048
(10:24:03) GdkPixbuf: 	Copy pixels == false
(10:24:03) GdkPixbuf: gdk_pixbuf_from_pixdata() called on:
(10:24:03) GdkPixbuf: 	Encoding raw
(10:24:03) GdkPixbuf: 	Dimensions: 16 x 16
(10:24:03) GdkPixbuf: 	Rowstride: 64, Length: 1048
(10:24:03) GdkPixbuf: 	Copy pixels == false
(10:24:05) GLib: Source ID 34199 was not found when attempting to remove it
(10:24:08) GLib: Source ID 37732 was not found when attempting to remove it
(10:24:08) util: Writing file prefs.xml to directory /home/kurnevsky/.purple
(10:24:08) util: Writing file /home/kurnevsky/.purple/prefs.xml
(10:24:10) jabber: Sending (ssl) (kurnevsky@jabber.ru/Pidgin): <message type='chat' id='purpleb3d79f03' to='<...>'><composing xmlns='http://jabber.org/protocol/chatstates'/></message>
(10:24:11) lurch: retrieved devicelist for <...>:
<publish node="eu.siacs.conversations.axolotl.devicelist"><item><list
xmlns="eu.siacs.conversations.axolotl"><device id="918664164" /><device
id="1258206565" /><device id="1575433349" /></list></item></publish>

(10:24:11) lurch: retrieved own devicelist:
<publish node="eu.siacs.conversations.axolotl.devicelist"><item><list
xmlns="eu.siacs.conversations.axolotl" /></item></publish>

(10:24:11) lurch: lurch_message_encrypt_im: no own devicelist (0)
(10:24:11) g_log: xmlnode_to_str_helper: assertion 'node != NULL' failed
(10:24:11) g_log: jabber_send_raw: assertion 'data != NULL' failed
(10:24:11) jabber: Sending (ssl) (kurnevsky@jabber.ru/Pidgin): <message type='chat' id='purpleb3d79f05' to='<...>'><active xmlns='http://jabber.org/protocol/chatstates'/></message>
(10:24:11) jabber: Sending (ssl) (kurnevsky@jabber.ru/Pidgin): <iq type='get' id='purpleb3d79f06'><ping xmlns='urn:xmpp:ping'/></iq>
(10:24:11) jabber: Recv (ssl)(98): <iq from='kurnevsky@jabber.ru' to='kurnevsky@jabber.ru/Pidgin' id='purpleb3d79f06' type='result'/>
```

**Comment by gkdr** [comment] 2017-02-28 09:52
Okay, so it is not a database error but there is really no devicelist.
There are two PEP nodes per device - a bundle and a devicelist. I upload the bundle first, and maybe your server then blocks the second, which is the devicelist.

Can you please open the debug log right after starting Pidgin (or just leave it open before closing it, it should open automatically then) and tell me which messages are sent during startup?
You're looking for the following message:
`(10:46:31) lurch: lurch_bundle_publish_own: published own bundle for a@localhost`
But around it it should also say something about the devicelist, and I need the raw XML too.

**Comment by kurnevsky** [comment] 2017-02-28 10:51
Is that it?
```
(13:16:43) lurch: lurch_pep_devicelist_event_handler: kurnevsky@jabber.ru received devicelist update from <...>
(13:16:43) lurch: lurch_devicelist_process: processing devicelist from <...> for kurnevsky@jabber.ru
(13:16:43) lurch: lurch_devicelist_process: cached devicelist is
<publish node="eu.siacs.conversations.axolotl.devicelist"><item><list
xmlns="eu.siacs.conversations.axolotl"><device id="918664164" /><device
id="1258206565" /><device id="1575433349" /></list></item></publish>
...
(13:16:43) jabber: Recv (ssl)(413): <message from='<...>' to='kurnevsky@jabber.ru/Pidgin' type='headline' id='565b1b9cdcb15aec'><event xmlns='http://jabber.org/protocol/pubsub#event'><items node='eu.siacs.conversations.axolotl.devicelist'><item id='57dece358ebfe861'><list xmlns='eu.siacs.conversations.axolotl'><device id='733612656'/></list></item></items></event><delay xmlns='urn:xmpp:delay' stamp='2017-02-16T15:41:15Z'/></message>
(13:16:43) jabber: XML parser error for JabberStream 0xf4e160: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute
(13:16:43) lurch: lurch_pep_devicelist_event_handler: kurnevsky@jabber.ru received devicelist update from <...>
(13:16:43) lurch: lurch_devicelist_process: processing devicelist from <...> for kurnevsky@jabber.ru
(13:16:43) lurch: lurch_devicelist_process: cached devicelist is
<publish node="eu.siacs.conversations.axolotl.devicelist"><item><list
xmlns="eu.siacs.conversations.axolotl"><device id="733612656" /></list></item></publish>
...
(13:16:43) lurch: lurch_pep_own_devicelist_request_handler: preparing installation...
(13:16:43) lurch: lurch_pep_own_devicelist_request_handler: ...done
(13:16:43) lurch: lurch_pep_own_devicelist_request_handler: comparing received devicelist with cached one
(13:16:43) lurch: lurch_pep_own_devicelist_request_handler: failed to import received devicelist (-12000)
```

**Comment by gkdr** [comment] 2017-02-28 17:56
Yes! Apparently parsing the devicelist fails - the format is unexpected (somehow). Now I just need the raw XML of the incoming devicelist message so I can see what's going wrong.

**Comment by kurnevsky** [comment] 2017-03-01 08:38
@gkdr here is request-response:
```
(11:27:52) jabber: Sending (ssl) (kurnevsky@jabber.ru/Pidgin): <iq type='get' id='purple46f76552' to='kurnevsky@jabber.ru'><pubsub xmlns='http://jabber.org/protocol/pubsub'><items node='eu.siacs.conversations.axolotl.devicelist' max_items='1'/></pubsub></iq>
(11:27:53) jabber: Recv (ssl)(218): <iq from='kurnevsky@jabber.ru' to='kurnevsky@jabber.ru/Pidgin' id='purple46f76552' type='result'><pubsub xmlns='http://jabber.org/protocol/pubsub'><items node='eu.siacs.conversations.axolotl.devicelist'/></pubsub></iq>
```

**Comment by gkdr** [comment] 2017-03-01 13:01
Thanks, I will try to reproduce why this causes the parsing error (-12000).

**Comment by kurnevsky** [comment] 2017-03-01 16:28
@gkdr btw, I don't see any device id in the responce. Is it the one you were looking for?

**Comment by gkdr** [comment] 2017-03-02 00:13
The client initialization starts by requesting the own devicelist from the server, in case you already use OMEMO with other accounts. Your own ID is then appended to the (empty) devicelist and uploaded. But since it somehow fails to parse the empty devicelist, it will not upload it either.

I'll be back home tomorrow so I can look at it then.

**Comment by gkdr** [comment] 2017-03-02 22:52
The servers I used to test it with all use Prosody, and the empty reply had an `<item>` tag inside the `<items>` tag which contained an empty `<list>` tag.
Your server only replied with an empty `<items>` tag, so my XML parsing got a bit confused.

Please tell me if it works now!

**Comment by kurnevsky** [comment] 2017-03-03 09:03
Yes, it works. Thanks!

**Closed** 2017-03-03 09:04 UTC
