### ISSUE TITLE
lurch - received omemo message that does not contain a key for this device, skipping

### ISSUE THREAD

**Issue by razzor1984** [gkdr/lurch#28] opened 2017-02-26 09:32 UTC
Hello,
tried to test it with a friend, because he is a Windows user i thought ok, lets simply fey things an dont mix os types. So i build a Vm with windows 10 -v 1607 and installed lurch - same happened by my counterpart.(Os version & pidgin version )
Both pidgin versions have the cyperpunkt OTR plugin active.

After installing the lurch dlls (we both used only the lurch.dll not the compatible one) + carbon.dll - we tried to do a key exchange - bit its kind of fuzzy it seemed that for the first account a key was signed but then the encryption failed.

The second account was more challenging:
At the first sight the logs are fine but in the end lurch didn't receive device encryption keys.

How can i reset the OMEMO Keys so that i can try a clean slate approach?

the complete log from pidgin:

<Pidgin Debug Log : 25.02.2017 21:43:15
(21:42:13) lurch: retrieved devicelist for xxxxxxxxx:
<publish node="urn:xmpp:omemo:0:devicelist"><item><list
xmlns="urn:xmpp:omemo:0" /></item></publish>

(21:42:13) lurch: retrieved own devicelist:
<publish node="urn:xmpp:omemo:0:devicelist"><item><list
xmlns="urn:xmpp:omemo:0"><device id="xxxxxxxx" /></list></item></publish>

(21:42:13) lurch: lurch_message_encrypt_im: failed to malloc address struct (-1000001)
(21:42:13) g_log: xmlnode_to_str_helper: assertion `node != NULL' failed
(21:42:13) g_log: jabber_send_raw: assertion `data != NULL' failed
(21:42:14) util: Writing file prefs.xml to directory C:\Users\xxxxx\AppData\Roaming\.purple
(21:42:14) util: Writing file C:\Users\xxxxx\AppData\Roaming\.purple\prefs.xml
(21:42:16) prefs: /pidgin/debug/width changed, scheduling save.
(21:42:16) prefs: /pidgin/debug/height changed, scheduling save.
(21:42:18) jabber: Sending (ssl) (xxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxx): <iq type='get' id='xxxxxxxxxxxxxx'><ping xmlns='urn:xmpp:ping'/></iq>
(21:42:18) jabber: Recv (ssl)(103): <iq id='xxxxxxxxxxxxxxxx' type='result' to='xxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxx'/>
(21:42:21) util: Writing file prefs.xml to directory C:\Users\xxxxxxxxx\AppData\Roaming\.purple
(21:42:21) util: Writing file C:\Users\xxxxxxxx\AppData\Roaming\.purple\prefs.xml
(21:42:33) gtkconv: setting active conversation on toolbar 02FBA180
(21:42:36) lurch: retrieved devicelist for xxxxxxxxxxxxxxxxxx:
<publish node="urn:xmpp:omemo:0:devicelist"><item><list
xmlns="urn:xmpp:omemo:0"><device id="17xxxxxxx" /><device
id="19xxxxxx" /></list></item></publish>

(21:42:36) lurch: retrieved own devicelist:
<publish node="urn:xmpp:omemo:0:devicelist"><item><list
xmlns="urn:xmpp:omemo:0"><device id="13xxxxxxxxx" /></list></item></publish>

(21:42:36) lurch: lurch_msg_encrypt_for_addrs: trying to encrypt key for 2 devices
(21:42:36) lurch: lurch_key_encrypt: encrypting key for xxxxxxxxxxx:19xxxxxxxx
(21:42:36) lurch: lurch_key_encrypt: encrypting key for xxxxxxxxxxx:17xxxxxxxx
(21:42:36) jabber: Sending (ssl) (xxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxx): <message type='chat' id='xxxxxxxxx' to='xxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxx'><active xmlns='http://jabber.org/protocol/chatstates'/><body>You received an OMEMO encrypted message, but your client does not support it.</body><html xmlns='http://jabber.org/protocol/xhtml-im'><body xmlns='http://www.w3.org/1999/xhtml'><p>?OTRv23?
<span style='font-weight: bold;'>xxxxxxxxxxxxx/</span> has requested an <a href='https://otr.cypherpunks.ca/'>Off-the-Record private conversation</a>.  However, you do not have a plugin to support that.
See <a href='https://otr.cypherpunks.ca/'>https://otr.cypherpunks.ca/</a> for more information.</p></body></html><encrypted xmlns='urn:xmpp:omemo:0'><header sid='13xxxxx'><key rid='17xxxxxxx'>MwgtEiEFN+z6SYuPOLgoyUhovP8mUdbmKKulaYaC2TTMIQrs7mkaIQX6UXhRxCb8BbSd5t1d/eIJnNXmGFDVjXeyBIDLmy2XcSJSMwohBU43Hk3Ox5DzSoLtY+/q/qM2eYKcL/LCdi2hLaXyuv4xEAoYACIgwqfRxOkcH7hfp0yOVi65IqgkE//KIHy7x7XwzKkGH1z1AzI5RHBAjyiDmo37BDAB</key><key rid='19xxxxxxx'>MwhgEiEFhj81JKkF29GckzGGDCrkSa8ln7pjVFc/M5HPQzF85hcaIQX6UXhRxCb8BbSd5t1d/eIJnNXmGFDVjXeyBIDLmy2XcSJSMwohBTgcvqwUTMBbb2rQ0jJQrS2CyrIwU7heX+nhrD+52hVyEAoYACIgRLWEKx3x1IvKNVY+MKFpMvby1CQRmbNylwqC7yQajl4+mx2xPJPN7iiDmo37BDAA</key><iv>OxI8wpbgMnYub660+px6QQ==</iv></header><payload>BPhb2u91jNlFBUoiqqPEBaNsOwijo599U+wqDsGY7wwShyMt5Ok1BObeoA54Y6QFShittodgkZbC+BxJiNMw7z4lmmZvQ9shbKLEhKOo9/Di5KQFip9MZFVRjbfg8hwIBDunJJ9VZgyc5oHzGxT6NY3EkSlbM4AUfEkEFPUiDmMRhmV5fmXsVyG2q8U+RXR1nolx+I1UCR7obRF6uT1eC32quOAtunYeGNVkoY4bo+3Mh4YNeFYCMDxhhcrmaFvYi56JTv7k7cCr/DAyfjWIfrN+CERTCiiuErFkPdj4eFh8ml3fSZcKVSE=</payload></encrypted><store xmlns='urn:xmpp:hints'/></message>
(21:42:37) jabber: Recv (ssl)(1187): <message to='xxxxxxxx' from='xxxxx/xxxxxxx' type='chat' id='purplexxxxxx'><active xmlns='http://jabber.org/protocol/chatstates'/><encrypted xmlns='eu.siacs.conversations.axolotl'><header sid='19xxxxxx'><key rid='17xxxxxxxx'>MwgOEiEFPfuUju8g6w0GjuVrYhOAp+xW71hqkLwGqrzI3x2H6mUaIQXE9CqRtbPD5NPP4UkEDaX9fHcJjnjkeLteeUTmbL+ldyJSMwohBfXjJEVzoHaCdE3TSmrHHRT7z8hKQY5OD8aeqTncwMkREAwYACIg+f31wl+PxD7mFPlnptk9blbBN924la8zbEvbFhJ+UGT56g0RWBiD8Si7+f+tBzAB</key><iv>q7d1YJ52PYlwgamn/fxRCA==</iv></header><payload>ropaTJ4UJrvkAWb8OBYt1H6khHvEjKAId3Ops62KoiOUbOQG25lnBtYS2940Ay1Pp6hLQJsdFtqzoVRBaOjoimfgTvYzFy4p7hwVZ1ZDcgn8JCXkHpAdkEBBFws+UhA4Zi0Jr99oy/5NJLh8UPQYQ0iLJzMlwL51OMF17mxz/Ut1T4KKDChVeh42pQZMIcdjlNhTsK95yzocz6I2pPf8In/KyFi6QxuTvXRoA9O6gSXgOizbmxeqUmxcMOnlhUCjkgBAmBgt1S1H30BEwdHwzAvzSijGKx1NBbum7THZ1w3syfnXv180O0S/Xf2gX2n7I31IhHuPz4+EQyrIYtPqufKfAidrC0fDRqTXTYhjRPqoTdm7DS44q/XJFeWU6tTbSf2Mu3VEMg+6xAXEhEVB1xoufdsbCJ0/Mizp9ZxeEYm74jyBBiLx9IW57uw92qy/+DRVJzN7kQDiQM8/tR19848S</payload></encrypted><store xmlns='urn:xmpp:hints'/><body>You received an OMEMO encrypted message, but your client does not support it.</body></message>
(21:42:37) jabber: XML parser error for JabberStream 02EB7320: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute
(21:42:37) lurch: received omemo message that does not contain a key for this device, skipping>

**Comment by gkdr** [comment] 2017-02-26 10:07
I'm not sure what you are trying to do with OTR here - the encryption is already built-in, so using OTR might confuse OMEMO.

The big problem here seems to be the following line though:
(21:42:13) lurch: lurch_message_encrypt_im: failed to malloc address struct (-1000001)`
It could be a VM issue (failing to allocate the memory somehow), but maybe there is something else going on and I was not very specific with the error message.

**Comment by gkdr** [comment] 2017-03-10 20:32
I believe we were both waiting on each other, so this did not progress.
Sorry, I thought it is clear I was asking you to try it again without OTR.
I also missed your question somehow.

>How can i reset the OMEMO Keys so that i can try a clean slate approach?

Inside Pidgin, type `/lurch uninstall yes` into any conversation window, then close Pidgin and delete the _your@jid.com_axc_db.sqlite_ and _your@jid.com_omemo_db.sqlite_ files. lurch should then regenerate everything when you open Pidgin the next time.

**Comment by gkdr** [comment] 2017-04-06 13:16
Since this is now over a month old and you didn't comment again, I'm going to close this issue to remove some clutter.
However, you're very welcome to comment and I'll reopen it if you do.

**Closed by gkdr** 2017-04-06 13:16 UTC

**Comment by l-n-s** [comment] 2017-08-23 12:56
We are trying to chat with buddy, but it shows this error message:

```
8:39:16 AM) Even though an encrypted session exists, the recipient's devicelist is empty.The user probably uninstalled OMEMO, so you can add this conversation to the blacklist.
(08:39:16 AM) There was an error encrypting the message and it was not sent. You can try again, or try to find the problem by looking at the debug log.
```

And log contains those lines:

```
(08:43:54) lurch: lurch_message_encrypt_im: failed to malloc address struct (-1000001)
(08:43:54) g_log: xmlnode_to_str_helper: assertion 'node != NULL' failed
(08:43:54) g_log: jabber_send_raw: assertion 'data != NULL' failed
```

We both use pidgin.

**Comment by gkdr** [comment] 2017-08-23 17:58
Can you confirm that you receive your friend's devicelist at startup? It could be a server issue.

**Comment by cmeng-git** [comment] 2021-08-20 02:27
I have the same problem. Pidgin can receive but cannot send OMEMO message with the above mentioned error message.

Found that the pidgin user account must only be created after the omemo plugin has been installed.
So I deleted the previously created user account, and recreate the account after omemo plugin has been installed; then everything work as normal.

**Comment by gkdr** [comment] 2021-08-21 21:11
hi @cmeng-git, thanks for reporting your workaround! maybe i can make something of that.

**Comment by Giermann** [comment] 2022-10-06 10:03
Any progress on this?
I just started to play around with OMEMO to chat between Pidgin and Quicksy/Conversations. But for some reason, lurch does not encrypt sent messages and displays the given error (no key for this device) on receiving encrypted messages.
I don't want to remove the user account, so how to solve this?

**Comment by gkdr** [comment] 2022-10-07 10:05
hey @Giermann,
it is unfortunately still an elusive issue. have you checked https://github.com/gkdr/lurch#troubleshooting to see what the actual problem is? do you know what software your xmpp server is running?

**Comment by Giermann** [comment] 2022-10-07 11:22
The problem "seems" to be, that there is no key being created for existing accounts...
After reading the above again, I changed my mind from "don't want to remove the user account", as I noticed that I only have to remove it from Pidgin and not the entire account on the server.
So I did what cmeng-git told: I removed the user account in Pidgin and recreated it.
Now it works for this account!
FYI: I tried the test between an account at Jabbers.one against an account at Quicksy.im - both seem to be 100% XMPP compliant.

Maybe you can find something interessing in the logs?

Receiving an OMEMO message with an existing account:
```
(12:39:27) jabber: Recv (ssl)(243): <message xml:lang='en' type='chat' to='r*****@jabbers.one' from='+491********94@quicksy.im/Quicksy.A_L1'><composing xmlns='http://jabber.org/protocol/chatstates'/><no-store xmlns='urn:xmpp:hints'/><no-storage xmlns='urn:xmpp:hints'/></message>
(12:39:27) psychic: not available, doing nothing
(12:39:36) jabber: Recv (ssl)(240): <message xml:lang='en' type='chat' to='r*****@jabbers.one' from='+491********94@quicksy.im/Quicksy.A_L1'><active xmlns='http://jabber.org/protocol/chatstates'/><no-store xmlns='urn:xmpp:hints'/><no-storage xmlns='urn:xmpp:hints'/></message>
(12:39:36) jabber: Recv (ssl)(1881): <message type='chat' from='+491********94@quicksy.im/Quicksy.A_L1' to='r*****@jabbers.one' id='5a4c180e-3d35-4f2a-ae8e-39814929fcb7' xml:lang='en'><encrypted xmlns='eu.siacs.conversations.axolotl'><header sid='898377310'><key rid='125002501'>MwohBW4e0PGwj9HJ40pJaxp3g0OybYnfQy86XkEbKko/OvpNEAEYASIwFcxmLw/gvnkRfJeym2nDVP37ym0jrin3cpL5jucuOm/RNzGzPI+jaemydOgwrOnzfBLOdOI/Olg=</key><key rid='10412'>MwohBUIzVgEHcxjLcnSv4Nc1FeKjUdYbZ+h+/63LtBnwtxp3EAMYAyIwSAAoxzewWfUnVsK8ophF2Y9NA570Btbhjg9LyX/XIbcjnLYQbvfxrm2zYFfGVx5sFi9h+BWKIPM=</key><key rid='1735984553'>MwohBf3K0eDNeQhEJ7IyHcShY2TNEGCVsrshG1M84EnnvJ0OEAQYACIwadV2DyB0XWU0vjnnwVgZIXA7HR6G20LrbuFiun2ILAVFfGJJEN9n9/IaaTkPEjsGPxWckBqGfPY=</key><key rid='262934909' prekey='true'>MwhMEiEFpbQ5zF6OECzOHuXHdHU3KK6kw8TVRhz6VqndLwetKHEaIQW4ldRZRiowuexbLqlAROlsgLVukUpUxXpdptZIdrhaRCJiMwohBScFpoWYhUAGd+1Io1h+gchuyUPEHMdmYa/h/64kl+VWEAMYACIwitxX6mCXSYoyq8pH4UJ8148cOl/5XD0mS3zZKTtfxsB9eLEbLPE0iXEQFBOfPtD+dkV9A+c/mUko3sywrAMwAA==</key><key rid='464586081' prekey='true'>MwgiEiEFjFMJXp5y6eafjznQk+6wxsihRuEDCxq1zBTIEhOR50IaIQW4ldRZRiowuexbLqlAROlsgLVukUpUxXpdptZIdrhaRCJiMwohBcxofwweLRS90xNxvQVPrHv6DWLs2s0dUtRX6mnFu/dIEAYYACIwNZUYux+H2B1lyxwpT8lDoWBlDLwE7CTJH4WJt8cZgBIXTKowZ0m+R+UjRr27qNdnXoQeA665Dq8o3sywrAMwAA==</key><iv>jOEGuxwYa7AESZf2</iv></header><payload>SxgD28y/T4wKug==</payload></encrypted><request xmlns='urn:xmpp:receipts'/><markable xmlns='urn:xmpp:chat-markers:0'/><origin-id id='5a4c180e-3d35-4f2a-ae8e-39814929fcb7' xmlns='urn:xmpp:sid:0'/><store xmlns='urn:xmpp:hints'/><encryption name='OMEMO' namespace='eu.siacs.conversations.axolotl' xmlns='urn:xmpp:eme:0'/><body>I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo</body><stanza-id xmlns='urn:xmpp:sid:0' id='2022-10-07-e2ed1afb1891fd53' by='r*****@jabbers.one'/></message>
(12:39:36) jabber: XML parser error for JabberStream 0573E1B0: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute
(12:39:36) lurch: received omemo message that does not contain a key for this device, skipping
```

Receiving a message after recreation of the account:
```
(12:47:26) jabber: Recv (ssl)(1953): <message xml:lang='en' to='+491********94@quicksy.im' from='r*****@jabbers.one/gajim.9GZCHSMO' type='chat' id='e573914f-5910-4002-8b9e-f91954488b0f'><archived by='+491********94@quicksy.im' id='1665139646552122' xmlns='urn:xmpp:mam:tmp'/><stanza-id by='+491********94@quicksy.im' id='1665139646552122' xmlns='urn:xmpp:sid:0'/><request xmlns='urn:xmpp:receipts'/><active xmlns='http://jabber.org/protocol/chatstates'/><markable xmlns='urn:xmpp:chat-markers:0'/><origin-id xmlns='urn:xmpp:sid:0' id='e573914f-5910-4002-8b9e-f91954488b0f'/><encrypted xmlns='eu.siacs.conversations.axolotl'><header sid='125002501'><key rid='262934909'>MwohBcpoGiFdG/weQ8P3Ysb8muLVa6P2PE/3sj52TSrIa4dgEAAYACIwdA8XW5NrMzZIHM9ordFxFNWgwARejfuYBplAJXb8kGGdMUWj+k23WGjIwrOnfMKTQBh8QCW1v8k=</key><key rid='898377310'>MwohBfwmlF9cXKiZKJhi9MLu+bSH69IhveANDBJwvXv/yPgmEAEYACIwv8E6F8vIXktLkUKqmDwV8hPWVRQLgF0idjIYwLdJQ/y4/s1nIgnTDCvXHiR5Abfq545sD+KDOgg=</key><key rid='1735984553'>MwohBfjq2o5xWdroSGGUrMn1BZmA/PcQP+rYVAZthYD4qINDEAIYACIw7d2YsxMKqix9xtsC7PpweTmD1ZTLkQyWDlVRsOvfBJDBPDIEPHA/iiBRX4dRAfydsbS87ReY8lc=</key><key rid='464586081' prekey='true'>MwgSEiEFxFcgwZtdsxDxoNhlkIcljuoIHEhtg8+1iWRW+5XK630aIQXSm3Sn0If0T58O8r98yiX5Eqw8g7J+e/FdRDnRAeLJSiJiMwohBZe87D5Offrr8ETVb8+Q1jb1Qr40aHlJEH5afJrHKy9UEAQYACIwkKrL5rIt2FnSY7WPTSiEjiT0s9D0wgvEYl5UAeKXsrN+z/qf8jcvP5361YJJ2NMnie5HUmY7u8kohcbNOzAA</key><key rid='10412' prekey='true'>Mwg9EiEFarhOfmXh4t9jBATlwh7ywbkGz8QUY2QPSVqCEFlF0j4aIQXSm3Sn0If0T58O8r98yiX5Eqw8g7J+e/FdRDnRAeLJSiJiMwohBf//EfiVYe18/ziiNuLwIbqZK3jEhfNSsJoRsYOowipWEAQYACIwX5b73RzZvZtJIeyIRRTSr7P0zdL6OK1P0J3tu6TyC9qSQ6gcq3qf2alyMcwHZ5Ucu06McGV5yf8ohcbNOzAA</key><iv>KXvD62LWOZeFk+8w</iv></header><payload>vgLFew==</payload></encrypted><encryption xmlns='urn:xmpp:eme:0' name='OMEMO' namespace='eu.siacs.conversations.axolotl'/><store xmlns='urn:xmpp:hints'/><body>You received a message encrypted with OMEMO but your client doesn&apos;t support OMEMO.</body></message>
(12:47:26) jabber: XML parser error for JabberStream 057E0E98: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute
(12:47:26) jabber: Recv (ssl)(26): <r xmlns='urn:xmpp:sm:3'/>
(12:47:26) jabber: Sending (ssl) (+491********94@quicksy.im/53015053999611795525396932738): <a xmlns='urn:xmpp:sm:3' h='43'/>
```

Unfortunately I don't have the same comparison for sending a message.
But after recreation, sending does just work fine - I do not have recreated my Jabbers.one account yet and when I try to send an OMEMO message with this, it does not appear in the Quicksy app at all and shows as "not encryptable" in Gajim.
Yesterday I received a "no key available" message in Pidgin when I tried to send OMEMO, today there's no error but obviously the message is not being encrypted properly.
Maybe I (or even you?) can reproduce the situation, with the following steps:
- remove Pidgin user account
- disable "lurch" PlugIn and delete any corresponding "omemo_*.db" files
- recreate Pidgin user account
- enable "lurch" PlugIn
- try to receive/send OMEMO messages, which should not work
- remove Pidgin user account
- recreate Pidgin user account
- try to receive/send OMEMO messages, which should be working now

**Comment by gnh1201** [comment] 2023-11-02 04:03
I also have the same issue, so I came to this issue page.

The first message was successfully encrypted with OMEMO after installing the lurch plugin.

However, when a message is sent from another client app supporting OMEMO (e.g., Conversations) afterward, the OMEMO information held by lurch becomes unusable, and the server is providing me with the following message:

```
Even though an encrypted session exists, the recipient's devicelist is empty. The user probably uninstalled OMEMO, so you can add this conversation to the blacklist.
```

The server is using ejabberd.
