### ISSUE TITLE
Messages sent by 0.6.6 Windows build do not show up on Conversations

### ISSUE THREAD

**Issue by pannal** [gkdr/lurch#88] opened 2018-04-04 12:09 UTC
I'm on Pidgin Windows 2.12.0 - after upgrading to the newest lurch-0.6.6.dll from the binary source, lurch/OMEMO doesn't show up in Plugins anymore and /lurch is an unknown command.

Downgrading to the older lurch-compat.dll from the binary repository makes it work again.

https://github.com/gkdr/carbons/issues/18

**Comment by RayZopf** [comment] 2018-04-04 21:02
`\AppData\Roaming\.purple\plugins\lurch-0.6.6.dll is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?`

**Comment by EionRobb** [comment] 2018-04-06 01:51
Can you try with https://eion.robbmob.com/lurch/lurch.dll ?

**Comment by gkdr** [comment] 2018-04-15 08:54
Can you show us what a sent message looks like in the debug log? The important part is the namespace -
 the one Conversations expects produces an XML error, but that's just a mis-tagged warning.

**Comment by RayZopf** [comment] 2018-04-16 23:34
i played a bit with Gajim and Pidgin, sending messages forth and back to myself on one single account  - I get messages that seem to be sent but not received, i get messages that could not get decrypted ... really messed up

**Comment by gkdr** [comment] 2018-04-19 10:29
Sorry, I kinda missed your update because you edited it in and I didn't get an email about it.
Yeah, as I said before, the important part is the namespace, and because for a long time Conversations and all other clients didn't use the one that's in the XEP there has been some confusion.

@EionRobb compiled a new version, can you try again with the current https://eion.robbmob.com/lurch/lurch.dll?

**Comment by gkdr** [comment] 2018-04-21 17:37
I'm going to close this because it was confirmed fixed in #93, which turned out to be the same issue.

**Closed by gkdr** 2018-04-21 17:37 UTC

**Comment by RayZopf** [comment] 2018-04-22 07:47
tested 0.6.7 to exchange between my own Pidgin - Gajim (prio 0) and seems to work, ty!
only thing interfering is Pidgin plugin 'carbons' which leads to Pidgin receiving the message sent from Gajim - and additionally:
```
(09:38:31) 
There was an error decrypting an OMEMO message addressed to this device. See the debug log for details.
```

**Comment by gkdr** [comment] 2018-04-22 17:03
@RayZopf, can you please open a new issue for this? And copy the incoming message from the debug log so I can look at what's going on.
